language: node_js
node_js:
- node
branches:
  only:
    - prod
    - test
before_script:
- gcloud config set project `rocktech-210118`
- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
- gcloud auth activate-service-account --key-file client-secret.json
- npm install -g --silent @angular/cli
- npm install
script:
- npm run pug-it
- ng build --prod
if: branch = test
  - gcloud compute scp . jorge_diaz@rocktech:/var/www/html/rocktech-client-test
if: branch = prod
  - gcloud compute scp . jorge_diaz@rocktech:/var/www/html/rocktech-client

notifications:
email:
  on_failure: change
  on_success: change
before_install:
- openssl aes-256-cbc -K $encrypted_0024339acafd_key -iv $encrypted_0024339acafd_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
