language: node_js
node_js:
- node
# safelist
branches:
  only:
  - master
  - test
  - prod
  
cache:
  directories:
  - "$HOME/google-cloud-sdk/"

before_script:
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk" ]; then
    export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)";
    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list;
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - ;
    sudo apt-get update && sudo apt-get install google-cloud-sdk;
  fi
- gcloud config set project `rocktech-210118`
- gcloud auth activate-service-account --key-file client-secret.json
- npm install -g --silent @angular/cli
- npm install

stages: 
- test
- prod

jobs:
  include:
    - stage: test
      script:
      - npm run pug-it
      - ng build --prod
      - gcloud compute scp . jorge_diaz@rocktech:/var/www/html/rocktech-client-test
    - stage: prod
      script:
      - npm run pug-it
      - ng build --prod
      - gcloud compute scp . jorge_diaz@rocktech:/var/www/html/rocktech-client-test

stages:
  - name: test
    if: branch = test
  - name: prod
    if: branch = prod
  

notifications:
email:
  on_failure: change
  on_success: change
before_install:
- openssl aes-256-cbc -K $encrypted_0024339acafd_key -iv $encrypted_0024339acafd_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
