language: node_js
node_js:
- node
branches:
  only:
  - master
  - test
  - prod
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
before_script:
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk" ]; then export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release
  -c -s)"; echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" |
  sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list; curl https://packages.cloud.google.com/apt/doc/apt-key.gpg
  | sudo apt-key add - ; sudo apt-get update && sudo apt-get install google-cloud-sdk;
  fi
- npm install -g --silent @angular/cli
- npm install
- tar -xzf credentials.tar.gz
- ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine
- gcloud config set project 'rocktech-210118'
- gcloud auth activate-service-account --key-file client-secret.json
- npm run pug-it
- ng build

stages:
- name: test
  if: branch = test
- name: prod
  if: branch = prod
jobs:
  include:
  - stage: test
    script:
    - gcloud compute scp --recurse ./dist jorge_diaz@rocktech:/var/www/html/dist-rocktech-test
      --zone us-east1-b
    - gcloud compute ssh jorge_diaz@rocktech --zone us-east1-b -- '(rm -rf /var/www/html/rocktech-client-test || true)
      && mkdir /var/www/html/rocktech-client-test && mv /var/www/html/dist-rocktech-test
      /var/www/html/rocktech-client-test/dist'
  - stage: prod
    script:
    - gcloud compute scp --recurse ./dist jorge_diaz@rocktech:/var/www/html/dist-rocktech
      --zone us-east1-b
    - gcloud compute ssh jorge_diaz@rocktech --zone us-east1-b -- '(rm -rf /var/www/html/rocktech-client || true)
      && mkdir /var/www/html/rocktech-client && mv /var/www/html/dist-rocktech
      /var/www/html/rocktech-client/dist'
notifications: 
email:
  on_failure: change
  on_success: change
before_install:
- openssl aes-256-cbc -K $encrypted_0024339acafd_key -iv $encrypted_0024339acafd_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
